# This is the hw.tcl file for 'MCC150_TransmitterBPSK'
# Generated by High Level Design Compiler for Intel(R) FPGAs 

package require -exact qsys 14.1

# module MCC150_TransmitterBPSK
set_module_property NAME MCC150_TransmitterBPSK
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property GROUP "Altera DSP Builder Advanced"
set_module_property DISPLAY_NAME MCC150_TransmitterBPSK
set_module_property EDITABLE false

# filesets
add_fileset DSPBA_QUARTUS_SYNTH QUARTUS_SYNTH quartus_synth_callback
set_fileset_property DSPBA_QUARTUS_SYNTH TOP_LEVEL MCC150_TransmitterBPSK

proc quartus_synth_callback {entity_name} {
	add_fileset_file "dspba_library_package.vhd" VHDL PATH "$::env(QUARTUS_ROOTDIR)/dspba/backend/Libraries/vhdl/base/dspba_library_package.vhd"
	add_fileset_file "dspba_library.vhd" VHDL PATH "$::env(QUARTUS_ROOTDIR)/dspba/backend/Libraries/vhdl/base/dspba_library.vhd"
	add_fileset_file "MCC150_TransmitterBPSK_safe_path_flat.vhd" VHDL PATH "MCC150_TransmitterBPSK_safe_path_flat.vhd"
	add_fileset_file "MCC150_TransmitterBPSK.vhd" VHDL PATH "MCC150_TransmitterBPSK.vhd"
	add_fileset_file "MCC150_TransmitterBPSK_Modulator.vhd" VHDL PATH "MCC150_TransmitterBPSK_Modulator.vhd"
	add_fileset_file "MCC150_TransmitterBPSK_PRBSGenerator.vhd" VHDL PATH "MCC150_TransmitterBPSK_PRBSGenerator.vhd"
	add_fileset_file "MCC150_TransmitterBPSK_PRBSGenerator_DualMem.hex" HEX PATH "MCC150_TransmitterBPSK_PRBSGenerator_DualMem.hex"
}
add_fileset DSPBA_SIM_VERILOG SIM_VERILOG sim_verilog_callback
set_fileset_property DSPBA_SIM_VERILOG TOP_LEVEL MCC150_TransmitterBPSK

proc sim_verilog_callback {entity_name} {
	add_fileset_file "dspba_library_package.vhd" VHDL PATH "$::env(QUARTUS_ROOTDIR)/dspba/backend/Libraries/vhdl/base/dspba_library_package.vhd"
	add_fileset_file "dspba_library.vhd" VHDL PATH "$::env(QUARTUS_ROOTDIR)/dspba/backend/Libraries/vhdl/base/dspba_library.vhd"
	add_fileset_file "MCC150_TransmitterBPSK_safe_path_flat.vhd" VHDL PATH "MCC150_TransmitterBPSK_safe_path_flat.vhd"
	add_fileset_file "MCC150_TransmitterBPSK.vhd" VHDL PATH "MCC150_TransmitterBPSK.vhd"
	add_fileset_file "MCC150_TransmitterBPSK_Modulator.vhd" VHDL PATH "MCC150_TransmitterBPSK_Modulator.vhd"
	add_fileset_file "MCC150_TransmitterBPSK_PRBSGenerator.vhd" VHDL PATH "MCC150_TransmitterBPSK_PRBSGenerator.vhd"
	add_fileset_file "MCC150_TransmitterBPSK_PRBSGenerator_DualMem.hex" HEX PATH "MCC150_TransmitterBPSK_PRBSGenerator_DualMem.hex"
}
add_fileset DSPBA_SIM_VHDL SIM_VHDL sim_vhdl_callback
set_fileset_property DSPBA_SIM_VHDL TOP_LEVEL MCC150_TransmitterBPSK

proc sim_vhdl_callback {entity_name} {
	add_fileset_file "dspba_library_package.vhd" VHDL PATH "$::env(QUARTUS_ROOTDIR)/dspba/backend/Libraries/vhdl/base/dspba_library_package.vhd"
	add_fileset_file "dspba_library.vhd" VHDL PATH "$::env(QUARTUS_ROOTDIR)/dspba/backend/Libraries/vhdl/base/dspba_library.vhd"
	add_fileset_file "MCC150_TransmitterBPSK_safe_path_flat.vhd" VHDL PATH "MCC150_TransmitterBPSK_safe_path_flat.vhd"
	add_fileset_file "MCC150_TransmitterBPSK.vhd" VHDL PATH "MCC150_TransmitterBPSK.vhd"
	add_fileset_file "MCC150_TransmitterBPSK_Modulator.vhd" VHDL PATH "MCC150_TransmitterBPSK_Modulator.vhd"
	add_fileset_file "MCC150_TransmitterBPSK_PRBSGenerator.vhd" VHDL PATH "MCC150_TransmitterBPSK_PRBSGenerator.vhd"
	add_fileset_file "MCC150_TransmitterBPSK_PRBSGenerator_DualMem.hex" HEX PATH "MCC150_TransmitterBPSK_PRBSGenerator_DualMem.hex"
}

# interfaces
# Interface clock
add_interface clock clock end
set_interface_property clock ENABLED true
add_interface_port clock clk clk Input 1
add_interface_port clock areset reset_n Input 1

# Interface exp
add_interface exp conduit end
set_interface_property exp ENABLED true
add_interface_port exp I_out data_I_out Output 12
